import { sveltekit } from '@sveltejs/kit/vite';
import { SvelteKitPWA } from '@vite-pwa/sveltekit';
// audit PR-47: `defineConfig` comes from `vitest/config`, not `vite`. Vitest 5 stopped
// augmenting vite's own config type through `/// <reference types="vitest" />`, so the
// `test` block below no longer type-checks against vite's `defineConfig`. This is the
// documented migration and it is the same function, re-exported with the test types.
import { defineConfig } from 'vitest/config';
// Single source of truth for the IARC certificate — the same module the /guide
// page's "Age ratings" block renders from, so the manifest and the UI can never
// advertise different ratings. Dependency-free on purpose (see src/lib/ratings.ts).
import { IARC_RATING_ID } from './src/lib/ratings';

// PWA: app-shell offline support. Static assets are precached; the portal API
// (Cloudflare Worker) uses NetworkFirst so visitors always get fresh data when
// online but still see a usable shell + last-good data when offline.
export default defineConfig({
  plugins: [
    sveltekit(),
    SvelteKitPWA({
      registerType: 'autoUpdate',
      manifest: {
        // App identity — the stable manifest id for this PWA. Kept as '/' (it
        // must never change once published, or stores treat it as a NEW app).
        id: '/',
        // IARC age-rating certificate (Partner Center -> "Current Rating ID").
        // Lets the Microsoft Store / Google Play / PWABuilder reuse the ratings
        // already issued for this app instead of re-running the questionnaire.
        iarc_rating_id: IARC_RATING_ID,
        name: 'Navyuvak Chhath Puja Samiti',
        short_name: 'Chhath Puja',
        description:
          'Navyuvak Chhath Puja Samiti, Shaharpura — a read-only public transparency portal: every contribution, expense, loan and committee record, live and accountable. Faith • Unity • Transparency.',
        lang: 'en',
        dir: 'ltr',
        categories: ['finance', 'social', 'utilities'],
        theme_color: '#0b6b4f',
        background_color: '#ffffff',
        display: 'standalone',
        // audit PR-43: was 'portrait', which LOCKS an installed PWA to one orientation. WCAG
        // 1.3.4 (AA) requires content not be restricted that way: a phone clamped to a
        // wheelchair arm, or a tablet in a stand, is often fixed in landscape, and the portal
        // was simply unusable there. 'any' lets the device decide; the layout is responsive
        // already, which is what made the lock gratuitous.
        orientation: 'any',
        start_url: '/',
        scope: '/',
        // Display fallback chain: prefer standalone, then minimal-ui, then browser.
        display_override: ['standalone', 'minimal-ui'],
        // Single-instance: re-open focuses/navigates the existing window.
        launch_handler: { client_mode: 'navigate-existing' },
        // No native companion app — always prefer the web app itself.
        prefer_related_applications: false,
        related_applications: [],
        // Microsoft Edge side-panel support (a narrow read-only dashboard fits well).
        edge_side_panel: { preferred_width: 400 },
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
        ],
        // App-listing preview images (wide = desktop, narrow = mobile). Branded
        // placeholders generated by scripts/gen-screenshots.mjs; swap for real
        // product screenshots anytime without a code change.
        screenshots: [
          {
            src: '/screenshots/wide.png',
            sizes: '1280x720',
            type: 'image/png',
            form_factor: 'wide',
            label: 'Navyuvak Chhath Puja Samiti — transparency portal'
          },
          {
            src: '/screenshots/narrow.png',
            sizes: '720x1280',
            type: 'image/png',
            form_factor: 'narrow',
            label: 'Navyuvak Chhath Puja Samiti — transparency portal'
          }
        ],
        // Every shortcut carries an `icons` array. Without it, Android's long-press
        // app-shortcut menu shows a blank/generic glyph even though the app icon
        // itself is fine (the app icon comes from `icons` above; per-shortcut icons
        // are a SEPARATE field the spec requires for the shortcut menu).
        //
        // Shortcut icons MUST be OPAQUE. The app `icons` above are transparent RGBA
        // (color type 6) so the launcher can composite them on its own app tile; the
        // shortcut sheet does NOT composite — it draws the icon as-is, so pointing a
        // shortcut at the transparent icon-192.png renders a blank white square (the
        // artwork is dropped/cropped against the sheet's white background). We
        // therefore ship a dedicated 192x192 OPAQUE asset (`icon-shortcut-192.png`,
        // color type 2 RGB, generated by scripts/gen-shortcut-icon.mjs: the diya
        // composited over the solid brand background). `purpose: 'any'` because the
        // asset is a plain square, not a maskable safe-zone icon.
        shortcuts: [
          { name: 'Expenses', short_name: 'Expenses', description: 'View expense records', url: '/expenses', icons: [{ src: '/icons/icon-shortcut-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' }] },
          { name: 'Loans', short_name: 'Loans', description: 'View surplus loans and guarantors', url: '/loans', icons: [{ src: '/icons/icon-shortcut-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' }] },
          { name: 'Committee', short_name: 'Committee', description: 'View the committee members', url: '/committee', icons: [{ src: '/icons/icon-shortcut-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' }] },
          { name: 'Downloads', short_name: 'Downloads', description: 'Find receipts and certificates', url: '/downloads', icons: [{ src: '/icons/icon-shortcut-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' }] },
          { name: 'Donate Now', short_name: 'Donate', description: 'How to contribute', url: '/donate', icons: [{ src: '/icons/icon-shortcut-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' }] }
        ]
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,webp,avif,woff2}'],
        // Keep the first-visit background download small. None of these is needed to render or
        // run the app offline:
        //  - screenshots/ and the 512px icons are only read by the browser's install prompt
        //    (online); the 192/180px icons the app itself uses stay precached.
        //  - the Devanagari webfont (121 kB) is fetched on demand the first time Hindi is shown
        //    and then served from the 'chhath-fonts' cache (rule below), so English-only
        //    visitors never download it and Hindi still works offline after one use.
        // (globs are matched under .svelte-kit/output, i.e. behind a client/ prefix, hence **/)
        globIgnores: ['**/screenshots/**', '**/icons/icon-512*.png', '**/fonts/noto-sans-devanagari-*.woff2'],
        // Pull the push/notification event handlers into the generated service
        // worker. Kept as a separate static script (static/push-sw.js) on purpose:
        // the generated SW owns the precache manifest and the runtime-caching
        // rules below, and rewriting those as a hand-written injectManifest SW
        // would risk regressing caching behaviour that took several fixes to get
        // right. importScripts only ADDS listeners and leaves all of it untouched.
        importScripts: ['/push-sw.js'],
        runtimeCaching: [
          {
            // ---- Portal API: NETWORK ONLY (audit PUB-FE-01) ----
            //
            // This was NetworkFirst with a 6s timeout and a 24h cache. When the
            // network missed that deadline, workbox replayed a cached 200 — and the
            // client cannot tell such a response apart from a live one, so
            // `loadPortalData` stamped it `savedAt: now()`, marked it fresh and
            // cleared the stale badge. A finance/transparency portal would then
            // show yesterday's contributions under a brand-new "last updated"
            // time, which is worse than showing nothing.
            //
            // Offline still works, and now says so: the client keeps its own
            // localStorage snapshot with the timestamp of the fetch that produced
            // it, and surfaces it as explicitly stale. One cache, one owner, and
            // provenance the UI can be honest about.
            //
            // Scoped to the API WORKER host only — it used to match
            // /shaharpura\.com/, which also swallowed files-chhath.shaharpura.com
            // (the R2 file domain) and broke uploaded images.
            urlPattern: ({ url }) =>
              /(^|\.)workers\.dev$/.test(url.host) ||
              url.host === 'chhath-public-worker.shaharpura.com',
            handler: 'NetworkOnly'
          },
          // NOTE — deliberately NO runtimeCaching rule for the uploaded images
          // (R2 profile photos / donation QR on files-chhath.shaharpura.com, and
          // the Google-hosted popup images). Those hosts send NO CORS headers, so
          // when the service worker re-fetches them through a workbox strategy the
          // response is unusable and the image breaks — the classic "loads on the
          // first visit, disappears after a reload" symptom, because the SW only
          // takes control from the second load onwards. With no matching route,
          // workbox lets the request go straight to the network, exactly as it did
          // before the SW existed, so the images always load. (Trade-off: uploaded
          // images are not available offline; correctness wins.)
          {
            // Same-origin self-hosted fonts (the Devanagari one is not precached, see globIgnores).
            urlPattern: ({ url }) => url.pathname.startsWith('/fonts/') && url.pathname.endsWith('.woff2'),
            handler: 'CacheFirst',
            options: {
              cacheName: 'chhath-fonts',
              expiration: { maxEntries: 4, maxAgeSeconds: 60 * 60 * 24 * 365 }
            }
          }
        ]
      }
    })
  ],
  test: {
    // `node` stays the default: the api/derive/ranking/schema tests are pure TS and are
    // much faster without a DOM. A component test opts in per file with
    //   // @vitest-environment jsdom
    environment: 'node',
    include: ['src/**/*.{test,spec}.{js,ts}']
  },
  // Svelte ships separate server and client builds. Without this, `mount()` resolves to
  // the SSR build and throws `lifecycle_function_unavailable`, so no component behaviour
  // (focus, keyboard, ARIA wiring) could be tested at all. Gated on VITEST so the
  // production build keeps resolving exactly as before.
  resolve: process.env.VITEST ? { conditions: ['browser'] } : undefined
});
