<script lang="ts">
  import '../app.css';
  import { onMount } from 'svelte';
  import { initPortal } from '$lib/stores/portal';
  import Shell from '$lib/components/Shell.svelte';
  import AnnouncementPopup from '$lib/components/AnnouncementPopup.svelte';
  import ConsentBanner from '$lib/components/ConsentBanner.svelte'; // analytics-cookie choice
  import Seo from '$lib/components/Seo.svelte'; // per-route canonical + social + JSON-LD
  import { pwaInfo } from 'virtual:pwa-info';
  import { listenForSubscriptionChange } from '$lib/push';
  import { initInbox } from '$lib/stores/notifications';
  import { startSync } from '$lib/sync';
  import { browser } from '$app/environment';
  import { page } from '$app/stores';
  import { goto, afterNavigate } from '$app/navigation';
  import { pushPageView } from '$lib/analytics/pageview';

  let { children } = $props();

  // <link rel="manifest"> generated by @vite-pwa/sveltekit (app.html also carries a
  // static fallback link for pre-hydration crawlers).
  let webManifestLink = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');

  // GTM SPA page-view tracking (no-op on the server / before dataLayer exists).
  afterNavigate(() => {
    if (!browser) return;
    pushPageView($page.url.pathname + $page.url.search, document.title);
  });

  // The QR printed on every receipt / certificate opens the portal at the ROOT with
  // `?record=<id>`. Forward those to /verify, keeping the id, so every already-printed
  // QR keeps working.
  $effect(() => {
    if (!browser) return;
    const rec = $page.url.searchParams.get('record');
    if (rec && $page.url.pathname !== '/verify') {
      void goto(`/verify?record=${encodeURIComponent(rec)}`, { replaceState: true });
    }
  });

  onMount(() => {
    initPortal();
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({ immediate: true });
    });
    const stopSync = startSync();
    const stopPushListener = listenForSubscriptionChange();
    const stopInbox = initInbox();
    return () => {
      stopSync();
      stopPushListener();
      stopInbox();
    };
  });
</script>

<Seo />

<svelte:head>
  <!-- eslint-disable-next-line svelte/no-at-html-tags — trusted build-time string -->
  {@html webManifestLink}
</svelte:head>

<Shell>
  {@render children()}
</Shell>

<AnnouncementPopup />
<ConsentBanner />
